/// Firebase configuration for push notifications (FCM).
///
/// Called during bootstrap().
class FirebaseConfig {
  // TODO: Add Firebase configuration
  // Firebase options should be loaded from firebase_options.dart
  // generated by flutterfire configure
  
  static const bool enabled = false; // Set to true when Firebase is configured
}
